require "unicode_utils/char_name"

lane :fetch_emojis do
  emoji_fetcher(path: "./Themoji")
end

lane :app_store do |options|
  emoji = options[:emoji] || "😴"
  emoji_name = UnicodeUtils.char_name(emoji).downcase
  emoji_name_clean = emoji_name.gsub(" ", "-")
  plist_path = "Themoji/App.plist"

  ENV["EMOJI"] = emoji
  ENV["EMOJI_NAME"] = emoji_name
  ENV["EMOJI_NAME_CLEAN"] = emoji_name_clean
  set_info_plist_value(path: plist_path, key: "emoji", value: emoji)
  set_info_plist_value(path: plist_path, key: "emoji_name", value: emoji_name)
  
  # emoji_app_icon(emoji: emoji)
  appicon(appicon_image_file: 'Themoji/TemplateAppIcon.png', 
    appicon_path: 'Themoji/Assets.xcassets', appicon_devices: [:iphone, :ipad])

  produce(app_name: emoji_name, sku: emoji_name_clean)
  match
  gym
end

lane :all do
  emojis.each do |current_emoji|
    app_store(emoji: current_emoji)
  end  
end

# Private lanes below

private_lane :emojis do
  ["🚀", "🎉"]
end
