require "unicode_utils/char_name"

lane :fetch_emojis do
  emoji_fetcher(path: "./Themoji")
end

lane :app_store do |options|
  emoji = options[:emoji] || "😴"
  emoji_name = UnicodeUtils.char_name(emoji).downcase
  emoji_name_clean = emoji_name.gsub(" ", "-")
  plist_path = "Themoji/App.plist"
  version = "1.0"

  ENV["EMOJI"] = emoji
  ENV["EMOJI_NAME"] = emoji_name
  ENV["EMOJI_NAME_CLEAN"] = emoji_name_clean
  set_info_plist_value(path: plist_path, key: "emoji", value: emoji)
  set_info_plist_value(path: plist_path, key: "emoji_name", value: emoji_name)
  
  # emoji_app_icon(emoji: emoji) # TODO
  appicon(appicon_image_file: 'Themoji/TemplateAppIcon.png', 
          appicon_path: 'Themoji/Assets.xcassets', 
          appicon_devices: [:iphone, :ipad])

  snapshot

  produce(app_name: emoji_name, sku: emoji_name_clean)
  match
  gym

  add_git_tag(tag: ["themoji", emoji_name_clean, version].join("-"))
  deliver(
    name: { 'en-US' => "Themoji #{emoji_name}" },
    keywords: { 'en-US' => "Themoji, Emoji, #{emoji_name}, #{emoji_name_clean}, lol" },
    description: { 'en-US' => File.read("description.txt").gsub("[[EMOJI]]", emoji_name) }
  )
  clean_build_artifacts
end

lane :all do
  emojis.each do |current_emoji|
    app_store(emoji: current_emoji)
  end
end

# Private lanes below

private_lane :emojis do
  ["🚀", "🎉"]
end
